services:
  nginx:
    image: nginx
    container_name: paperstack
    ports:
    - 90:80
    volumes:
    - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    - ./nginx/logs/:/var/log/nginx
    networks:
    - tp

  api:
    build:
      context: ../Backend/Paper.Api/Paper.Api
      dockerfile: Dockerfile
    networks:
    - tp

  app:
    build:
      context: ../Front
      dockerfile: Dockerfile
    networks:
    - tp

networks:
  tp:  # Déclaration du réseau 'tp'
    driver: bridge