version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: paperstack_db
    environment:
      MYSQL_ROOT_PASSWORD: root_password # Remplace par un mot de passe sécurisé
      MYSQL_DATABASE: paperstack         # Nom de la base de données
      MYSQL_USER: root                   # Nom de l'utilisateur
      MYSQL_PASSWORD: root               # Mot de passe de l'utilisateur
    ports:
      - 3306:3306
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - tp

  nginx:
    image: nginx
    container_name: paperstack
    ports:
      - 90:80
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/logs/:/var/log/nginx
    networks:
      - tp

  api:
    build:
      context: ../Backend/Paper.Api/Paper.Api
      dockerfile: Dockerfile
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_NAME: paperstack
      DB_USER: root
      DB_PASSWORD: root
    networks:
      - tp
    depends_on:
      - db

  app:
    build:
      context: ../Front
      dockerfile: Dockerfile
    networks:
      - tp

volumes:
  db_data:
    # Ce volume contient les données de la base de données MySQL
  nginx:
    # Ce volume est utilisé pour stocker les fichiers de configuration Nginx et les logs

networks:
  tp:
    driver: bridge